default["mysql"]["root_password"] = 'passw0rd'
default["mysql"]["db_name"] = 'wordpress'
default["mysql"]["user"]["name"] = 'wordpress'
default["mysql"]["user"]["password"] = 'wordpress'
default["mysql"]["hostname"] = 'localhost'
